// correctionData.js
// 100種類の自動修正ルールを定義（各パターンは文字列として定義）
const correctionRules = [
  // 元の12件
  { pattern: "\\s{2,}", replacement: " " },
  { pattern: "\\n", replacement: " " },
  { pattern: "([ぁ-ん]+)、([ぁ-ん]+)", replacement: "$1$2" },
  { pattern: "は、ひふへほ", replacement: "はひふへほ" },
  { pattern: "、{2,}", replacement: "、" },
  { pattern: "。{2,}", replacement: "。" },
  { pattern: "！{2,}", replacement: "！" },
  { pattern: "？{2,}", replacement: "？" },
  { pattern: "(\\d+)\\s+(\\d+)", replacement: "$1,$2" },
  { pattern: "ａｂｃ", replacement: "abc" },
  { pattern: "てて", replacement: "って" },
  { pattern: "すす", replacement: "す" },

  // 追加88件（誤字・重複・文法ミス・簡単方言など）
  { pattern: "だう", replacement: "どう" },
  { pattern: "はた", replacement: "また" },
  { pattern: "たは", replacement: "たのは" },
  { pattern: "をを", replacement: "を" },
  { pattern: "がが", replacement: "が" },
  { pattern: "でで", replacement: "で" },
  { pattern: "にに", replacement: "に" },
  { pattern: "のの", replacement: "の" },
  { pattern: "とと", replacement: "と" },
  { pattern: "かか", replacement: "か" },
  { pattern: "んん", replacement: "ん" },
  { pattern: "なな", replacement: "な" },
  { pattern: "らら", replacement: "ら" },
  { pattern: "けけ", replacement: "け" },
  { pattern: "ようよう", replacement: "よう" },
  { pattern: "たりたり", replacement: "たり" },
  { pattern: "ますます", replacement: "ます" },
  { pattern: "するする", replacement: "する" },
  { pattern: "いるいる", replacement: "いる" },
  { pattern: "ことこと", replacement: "こと" },
  { pattern: "してして", replacement: "して" },
  { pattern: "されされ", replacement: "され" },
  { pattern: "思います思います", replacement: "思います" },
  { pattern: "でしたでした", replacement: "でした" },
  { pattern: "ですです", replacement: "です" },
  { pattern: "こんにちはこんにちは", replacement: "こんにちは" },
  { pattern: "ありがとうありがとう", replacement: "ありがとう" },
  { pattern: "いです", replacement: "いいです" },
  { pattern: "おいしいい", replacement: "おいしい" },
  { pattern: "うまいです", replacement: "おいしいです" },
  { pattern: "ないない", replacement: "ない" },
  { pattern: "ことがあること", replacement: "ことがある" },
  { pattern: "たいと思います", replacement: "たいです" },
  { pattern: "することができます", replacement: "できます" },
  { pattern: "みたいな感じ", replacement: "のような感じ" },
  { pattern: "なんか", replacement: "なにか" },
  { pattern: "かも知れない", replacement: "かもしれない" },
  { pattern: "いっしょに", replacement: "一緒に" },
  { pattern: "すごく", replacement: "とても" },
  { pattern: "ほんと", replacement: "本当" },

  // 方言（関西弁、博多弁、名古屋弁、津軽弁の簡単補正）
  { pattern: "やけん", replacement: "だから" },
  { pattern: "ほやけど", replacement: "だけど" },
  { pattern: "やん", replacement: "じゃん" },
  { pattern: "〜しとる", replacement: "〜している" },
  { pattern: "〜しとん", replacement: "〜している" },
  { pattern: "〜やんけ", replacement: "〜じゃないか" },
  { pattern: "〜やねん", replacement: "〜なのだ" },
  { pattern: "〜しとるけん", replacement: "〜しているから" },
  { pattern: "〜やろ", replacement: "〜でしょう" },
  { pattern: "〜けん", replacement: "〜から" },
  { pattern: "〜っちゃ", replacement: "〜だよ" },
  { pattern: "〜ばい", replacement: "〜だよ" },
  { pattern: "〜とよ", replacement: "〜だよ" },
  { pattern: "〜やで", replacement: "〜だよ" },
  { pattern: "〜わ", replacement: "〜よ" },
  { pattern: "〜と？", replacement: "〜なの？" },
  { pattern: "〜しよる", replacement: "〜している" },
  { pattern: "〜ちゅう", replacement: "〜している" },
  { pattern: "〜せんと", replacement: "〜しないと" },
  { pattern: "〜せん", replacement: "〜しない" },
  { pattern: "〜しとき", replacement: "〜しておきなさい" },
  { pattern: "〜しとかな", replacement: "〜しておかないと" },
  { pattern: "なんしよん", replacement: "何してるの" },
  { pattern: "どこいきよん", replacement: "どこ行ってるの" },
  { pattern: "〜け？", replacement: "〜か？" },
  { pattern: "ほんま", replacement: "本当" },
  { pattern: "ちゃう", replacement: "違う" },
  { pattern: "せやな", replacement: "そうだな" },
  { pattern: "せやで", replacement: "そうだよ" },
  { pattern: "〜やさかい", replacement: "〜だから" },
  { pattern: "〜しやんと", replacement: "〜しないと" },
  { pattern: "〜やろか", replacement: "〜でしょうか" },
  { pattern: "〜しぃや", replacement: "〜しなさい" },
  { pattern: "〜してまう", replacement: "〜してしまう" },
  { pattern: "〜してしもた", replacement: "〜してしまった" },
  { pattern: "あかん", replacement: "だめ" },
  { pattern: "ほんまに", replacement: "本当に" },
  { pattern: "しんどい", replacement: "疲れた" },

  // ネットスラング軽減
  { pattern: "りょ", replacement: "了解" },
  { pattern: "おｋ", replacement: "OK" },
  { pattern: "乙", replacement: "お疲れ様" },
  { pattern: "わろた", replacement: "笑った" },
  { pattern: "ｗ{2,}", replacement: "笑" },
];
